# name: Scraper

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "15 22 * * 5"
# permissions:
#   contents: write

# jobs:
#   scrape:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out this repo
#         uses: actions/checkout@v2                                                               
#       - name: Set up Python 3.9                               
#         uses: actions/setup-python@master                               
#         with:                                 
#           python-version: '3.9'
#           cache: 'pip'
  
#       - name: 💿 Install Requirements                             
#         run: pip install -r requirements.txt
        
#       - name: 🍳 Scrape bom
#         run: python3 api_scraper.py
        
#       - name: 🚀 Commit and push if it changed
#         run: |
#           git config user.name "${GITHUB_ACTOR}"
#           git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#           git add -A
#           timestamp=$(date -u)
#           git commit -m "Latest data: ${timestamp}" || exit 0
#           git push
